# Generated by Django 5.1.5 on 2025-01-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_comptable',
            field=models.BooleanField(default=False, help_text='Check if this role is : comptable'),
        ),
    ]
